// webview-ui/src/views/SetupView.tsx
/**
 * @refresh reset
 */
import React, { useState, useEffect } from 'react'; // Import useState, useEffect
import { useConfig } from '../contexts/ConfigContext'; // Use Context hook

// Mock provider options - ideally fetch these or define centrally
const providerOptions = [
  { value: 'google', label: 'Google Gemini' },
  { value: 'openai', label: 'OpenAI' },
  { value: 'anthropic', label: 'Anthropic' },
  { value: 'ollama', label: 'Ollama' },
  // Add other providers as needed
];

// Mock model options per provider - ideally fetch or define centrally
const modelOptions: { [key: string]: { value: string; label: string }[] } = {
  google: [
    { value: 'gemini-1.5-flash-latest', label: 'Gemini 1.5 Flash' },
    { value: 'gemini-1.5-pro-latest', label: 'Gemini 1.5 Pro' },
    { value: 'gemini-1.0-pro', label: 'Gemini 1.0 Pro' },
  ],
  openai: [
    { value: 'gpt-4o', label: 'GPT-4o' },
    { value: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
    { value: 'gpt-3.5-turbo', label: 'GPT-3.5 Turbo' },
  ],
  anthropic: [
    { value: 'claude-3-5-sonnet-20240620', label: 'Claude 3.5 Sonnet' },
    { value: 'claude-3-opus-20240229', label: 'Claude 3 Opus' },
    { value: 'claude-3-haiku-20240307', label: 'Claude 3 Haiku' },
  ],
  ollama: [
    { value: 'llama3', label: 'Llama 3' },
    { value: 'mistral', label: 'Mistral' },
    { value: 'custom', label: 'Custom Model ID...' }, // Option for custom input
  ],
};


const SetupView: React.FC = () => {
  // Use context hook
  const { state, saveConfiguration, resetError } = useConfig();
  const { isLoading, error, provider, modelId, baseUrl } = state; // Destructure state

  // Local form state
  const [selectedProvider, setSelectedProvider] = useState(state.provider || ''); // Use state.provider
  const [selectedModelId, setSelectedModelId] = useState(state.modelId || ''); // Use state.modelId
  const [customModelId, setCustomModelId] = useState('');
  const [apiKey, setApiKey] = useState(''); // API Key is not stored in Zustand state directly
  const [selectedBaseUrl, setSelectedBaseUrl] = useState(state.baseUrl || ''); // Use state.baseUrl

  // Update local state if store changes (e.g., after initial load)
   useEffect(() => {
     setSelectedProvider(provider || '');
     setSelectedModelId(modelId || '');
     setSelectedBaseUrl(baseUrl || '');
   }, [state.provider, state.modelId, state.baseUrl]); // Use state properties in dependency array

  // Determine if custom model ID input should be shown
  const showCustomModelInput = selectedProvider === 'ollama' && selectedModelId === 'custom';
  // Determine if API key is needed (e.g., not for Ollama by default)
  const needsApiKey = selectedProvider && selectedProvider !== 'ollama';
   // Determine if Base URL is needed (e.g., only for Ollama or custom providers)
  const needsBaseUrl = selectedProvider === 'ollama';


  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    resetError(); // Clear previous errors

    const finalModelId = showCustomModelInput ? customModelId : selectedModelId;

    if (!selectedProvider || !finalModelId || (needsApiKey && !apiKey)) {
      // Basic validation feedback (could be more sophisticated)
      alert('Please fill in all required fields.');
      return;
    }

    saveConfiguration({
      provider: selectedProvider,
      modelId: finalModelId,
      apiKey: needsApiKey ? apiKey : null, // Only send API key if needed
      baseUrl: needsBaseUrl ? selectedBaseUrl : null, // Only send Base URL if needed
    });
  };

  return (
    <div className="p-4 border rounded bg-gray-50">
      <h2 className="text-lg font-semibold mb-3">Setup AI Provider</h2>
      {error && (
        <div className="mb-3 p-2 border border-red-400 bg-red-100 text-red-700 rounded">
          <span>Error: {error}</span>
          <button onClick={resetError} className="ml-2 text-sm font-bold">Dismiss</button>
        </div>
      )}
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Provider Selection */}
        <div>
          <label htmlFor="provider" className="block text-sm font-medium text-gray-700 mb-1">AI Provider</label>
          <select
            id="provider"
            value={selectedProvider}
            onChange={(e) => {
              setSelectedProvider(e.target.value);
              setSelectedModelId(''); // Reset model when provider changes
              setCustomModelId('');
              setApiKey('');
              setSelectedBaseUrl('');
            }}
            required
            className="w-full p-2 border rounded focus:ring-blue-500 focus:border-blue-500"
          >
            <option value="" disabled>Select a provider</option>
            {providerOptions.map(opt => (
              <option key={opt.value} value={opt.value}>{opt.label}</option>
            ))}
          </select>
        </div>

        {/* Model Selection (conditional based on provider) */}
        {selectedProvider && modelOptions[selectedProvider] && (
          <div>
            <label htmlFor="modelId" className="block text-sm font-medium text-gray-700 mb-1">Model ID</label>
            <select
              id="modelId"
              value={selectedModelId}
              onChange={(e) => setSelectedModelId(e.target.value)}
              required
              className="w-full p-2 border rounded focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="" disabled>Select a model</option>
              {modelOptions[selectedProvider].map(opt => (
                <option key={opt.value} value={opt.value}>{opt.label}</option>
              ))}
            </select>
          </div>
        )}

        {/* Custom Model ID Input (conditional) */}
        {showCustomModelInput && (
           <div>
             <label htmlFor="customModelId" className="block text-sm font-medium text-gray-700 mb-1">Custom Model ID</label>
             <input
               type="text"
               id="customModelId"
               value={customModelId}
               onChange={(e) => setCustomModelId(e.target.value)}
               required
               placeholder="e.g., my-custom-model"
               className="w-full p-2 border rounded focus:ring-blue-500 focus:border-blue-500"
             />
           </div>
        )}


        {/* API Key Input (conditional) */}
        {needsApiKey && (
          <div>
            <label htmlFor="apiKey" className="block text-sm font-medium text-gray-700 mb-1">API Key</label>
            <input
              type="password"
              id="apiKey"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              required
              placeholder="Enter your API Key"
              className="w-full p-2 border rounded focus:ring-blue-500 focus:border-blue-500"
            />
          </div>
        )}

         {/* Base URL Input (conditional) */}
         {needsBaseUrl && (
           <div>
             <label htmlFor="baseUrl" className="block text-sm font-medium text-gray-700 mb-1">Base URL (Optional for Ollama)</label>
             <input
               type="url"
               id="baseUrl"
               value={selectedBaseUrl}
               onChange={(e) => setSelectedBaseUrl(e.target.value)}
               placeholder="e.g., http://localhost:11434"
               className="w-full p-2 border rounded focus:ring-blue-500 focus:border-blue-500"
             />
           </div>
         )}

        {/* Submit Button */}
        <button
          type="submit"
          disabled={isLoading}
          className="px-3 py-1 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50"
        >
          {isLoading ? 'Saving...' : 'Save Configuration'}
        </button>
      </form>
    </div>
  );
};

export default SetupView;

// webview-ui/src/views/SetupView.vue
<script setup lang="ts">
import { computed, defineProps, defineEmits } from 'vue';

// Define props received from App.vue
const props = defineProps<{
  providerOptions: Array<any>;
  setupProvider: string;
  setupModelId: string;
  setupApiKey: string;
  setupBaseUrl: string;
  setupCustomModelId: string;
  configError: string | null;
  selectedProviderDetails: Record<string, any> | undefined;
  availableModels: Array<any>;
}>();

// Define emits to send updates back to App.vue
const emit = defineEmits([
  'update:setupProvider',
  'update:setupModelId',
  'update:setupApiKey',
  'update:setupBaseUrl',
  'update:setupCustomModelId',
  'saveConfiguration',
]);

// Local computed properties or methods specific to SetupView can go here if needed
// For now, we directly use props and emit events

</script>

<template>
  <div class="px-4 pb-6"> <!-- Adjusted padding -->
    <h2 class="mb-2 text-base font-light">Setup AI Provider</h2> <!-- Adjusted size/margin -->
    <p class="text-sm mb-6 opacity-80" style="color: var(--vscode-descriptionForeground, #7f7f7f);">Configure your AI provider to start using Apex Coder.</p> <!-- Adjusted opacity -->

    <!-- Provider Dropdown -->
    <div class="mb-5"> <!-- Adjusted margin -->
      <label for="provider-select" class="block mb-1.5 text-xs font-normal opacity-75" style="color: var(--vscode-descriptionForeground, #7f7f7f);">Provider</label> <!-- Adjusted font/opacity -->
      <select
        id="provider-select"
        :value="props.setupProvider"
        @input="emit('update:setupProvider', ($event.target as HTMLSelectElement).value)"
        class="w-full p-2.5 border border-transparent rounded-lg box-border text-sm focus:outline-none focus:ring-1 focus:ring-offset-1 focus:ring-opacity-50" <!-- Adjusted padding, border, rounding, focus -->
        style="background-color: var(--vscode-input-background, white); color: var(--vscode-input-foreground, black); border-color: var(--vscode-input-border, transparent); focus-ring-color: var(--vscode-focusBorder, #007fd4);"
        :style="{ 'border-color': 'var(--vscode-input-border, transparent)', 'box-shadow': 'none', '--focus-ring-color': 'var(--vscode-focusBorder, #007fd4)' }"
        @focus="($event.target as HTMLElement).style.borderColor = 'var(--vscode-focusBorder, #007fd4)'"
        @blur="($event.target as HTMLElement).style.borderColor = 'var(--vscode-input-border, transparent)'"
      >
        <option v-for="option in props.providerOptions" :key="option.value" :value="option.value">
          {{ option.label }}
        </option>
      </select>
    </div>

    <!-- Model Dropdown (conditional) -->
    <div class="mb-5" v-if="props.setupProvider && props.availableModels.length > 0"> <!-- Adjusted margin -->
      <label for="modelId-select" class="block mb-1.5 text-xs font-normal opacity-75" style="color: var(--vscode-descriptionForeground, #7f7f7f);">Model</label> <!-- Adjusted font/opacity -->
      <select
        id="modelId-select"
        :value="props.setupModelId"
        @input="emit('update:setupModelId', ($event.target as HTMLSelectElement).value)"
        class="w-full p-2.5 border border-transparent rounded-lg box-border text-sm focus:outline-none focus:ring-1 focus:ring-offset-1 focus:ring-opacity-50" <!-- Adjusted padding, border, rounding, focus -->
        style="background-color: var(--vscode-input-background, white); color: var(--vscode-input-foreground, black); border-color: var(--vscode-input-border, transparent); focus-ring-color: var(--vscode-focusBorder, #007fd4);"
        :style="{ 'border-color': 'var(--vscode-input-border, transparent)', 'box-shadow': 'none', '--focus-ring-color': 'var(--vscode-focusBorder, #007fd4)' }"
        @focus="($event.target as HTMLElement).style.borderColor = 'var(--vscode-focusBorder, #007fd4)'"
        @blur="($event.target as HTMLElement).style.borderColor = 'var(--vscode-input-border, transparent)'"
      >
         <option v-for="model in props.availableModels" :key="model.value" :value="model.value">
           {{ model.label }}
         </option>
      </select>
    </div>

    <!-- Custom Model ID Input (conditional, e.g., for Ollama) -->
     <div class="mb-5" v-if="props.selectedProviderDetails?.allowCustomModel"> <!-- Adjusted margin -->
       <label for="customModelId" class="block mb-1.5 text-xs font-normal opacity-75" style="color: var(--vscode-descriptionForeground, #7f7f7f);">Custom Model ID (if not in list)</label> <!-- Adjusted font/opacity -->
       <input
         type="text"
         id="customModelId"
         :value="props.setupCustomModelId"
         @input="emit('update:setupCustomModelId', ($event.target as HTMLInputElement).value)"
         placeholder="e.g., my-local-model:latest"
         class="w-full p-2.5 border border-transparent rounded-lg box-border text-sm focus:outline-none focus:ring-1 focus:ring-offset-1 focus:ring-opacity-50" <!-- Adjusted padding, border, rounding, focus -->
         style="background-color: var(--vscode-input-background, white); color: var(--vscode-input-foreground, black); border-color: var(--vscode-input-border, transparent); focus-ring-color: var(--vscode-focusBorder, #007fd4);"
         :style="{ 'border-color': 'var(--vscode-input-border, transparent)', 'box-shadow': 'none', '--focus-ring-color': 'var(--vscode-focusBorder, #007fd4)' }"
         @focus="($event.target as HTMLElement).style.borderColor = 'var(--vscode-focusBorder, #007fd4)'"
         @blur="($event.target as HTMLElement).style.borderColor = 'var(--vscode-input-border, transparent)'"
       >
     </div>

     <!-- API Key Input (conditional) -->
     <div class="mb-5" v-if="props.selectedProviderDetails?.requiresApiKey"> <!-- Adjusted margin -->
       <label for="apiKey" class="block mb-1.5 text-xs font-normal opacity-75" style="color: var(--vscode-descriptionForeground, #7f7f7f);">API Key</label> <!-- Adjusted font/opacity -->
       <input
         type="password"
         id="apiKey"
         :value="props.setupApiKey"
         @input="emit('update:setupApiKey', ($event.target as HTMLInputElement).value)"
         placeholder="Enter your API Key"
         class="w-full p-2.5 border border-transparent rounded-lg box-border text-sm focus:outline-none focus:ring-1 focus:ring-offset-1 focus:ring-opacity-50" <!-- Adjusted padding, border, rounding, focus -->
         style="background-color: var(--vscode-input-background, white); color: var(--vscode-input-foreground, black); border-color: var(--vscode-input-border, transparent); focus-ring-color: var(--vscode-focusBorder, #007fd4);"
         :style="{ 'border-color': 'var(--vscode-input-border, transparent)', 'box-shadow': 'none', '--focus-ring-color': 'var(--vscode-focusBorder, #007fd4)' }"
         @focus="($event.target as HTMLElement).style.borderColor = 'var(--vscode-focusBorder, #007fd4)'"
         @blur="($event.target as HTMLElement).style.borderColor = 'var(--vscode-input-border, transparent)'"
       >
     </div>

     <!-- Base URL Input (conditional) -->
     <div class="mb-5" v-if="props.selectedProviderDetails?.requiresBaseUrl"> <!-- Adjusted margin -->
       <label for="baseUrl" class="block mb-1.5 text-xs font-normal opacity-75" style="color: var(--vscode-descriptionForeground, #7f7f7f);">Base URL (Optional for Ollama)</label> <!-- Adjusted font/opacity -->
       <input
         type="text"
         id="baseUrl"
         :value="props.setupBaseUrl"
         @input="emit('update:setupBaseUrl', ($event.target as HTMLInputElement).value)"
         placeholder="e.g., http://localhost:11434"
         class="w-full p-2.5 border border-transparent rounded-lg box-border text-sm focus:outline-none focus:ring-1 focus:ring-offset-1 focus:ring-opacity-50" <!-- Adjusted padding, border, rounding, focus -->
         style="background-color: var(--vscode-input-background, white); color: var(--vscode-input-foreground, black); border-color: var(--vscode-input-border, transparent); focus-ring-color: var(--vscode-focusBorder, #007fd4);"
         :style="{ 'border-color': 'var(--vscode-input-border, transparent)', 'box-shadow': 'none', '--focus-ring-color': 'var(--vscode-focusBorder, #007fd4)' }"
         @focus="($event.target as HTMLElement).style.borderColor = 'var(--vscode-focusBorder, #007fd4)'"
         @blur="($event.target as HTMLElement).style.borderColor = 'var(--vscode-input-border, transparent)'"
       >
     </div>

     <!-- Error Message -->
     <div v-if="props.configError" class="my-5 p-3 rounded-lg text-xs" style="background-color: var(--vscode-inputValidation-errorBackground, #f8d7da); color: var(--vscode-inputValidation-errorForeground, #721c24); border: 1px solid var(--vscode-inputValidation-errorBorder, #f5c6cb);"> <!-- Adjusted margin/rounding -->
         Error: {{ props.configError }}
     </div>

    <button @click="emit('saveConfiguration')" class="w-full px-4 py-2.5 rounded-lg cursor-pointer transition-colors duration-200 text-sm font-medium leading-snug disabled:opacity-60 disabled:cursor-not-allowed hover:bg-opacity-85" style="background-color: var(--vscode-button-background, #007acc); color: var(--vscode-button-foreground, white); border: 1px solid var(--vscode-button-border, transparent);">Save Configuration</button> <!-- Adjusted padding, rounding, font, disabled state, hover -->
  </div>
</template>
